stages:
  - deploy_dev
  - deploy_prod

deploy_dev:
  stage: deploy_dev
  environment:
    name: development
  script:
    - echo TEXT_FILE=$TEXT_FILE_DEV > .env.local
    - echo BOT_TOKEN=$BOT_TOKEN_DEV >> .env.local
    - echo HTTP_URL=$HTTP_URL_DEV >> .env.local
    - echo LOGSTASH_TYPE=dev-c3po.sibset.ru >> .env.local
    - echo LOG_LEVEL=debug >> .env.local
    - npm i
    - cross-env DATABASE_URI=$DEV_SIB_DATABASE_URI node_modules/.bin/sequelize-cli db:migrate
    - pm2 startOrReload ecosystem.json --only server
    - pm2 startOrReload ecosystem.json --only worker
  only:
    - master
    - /^Web-/
  tags:
    - develop
  when: manual

deploy_prod:
  stage: deploy_prod
  environment:
    name: production
  script:
    - echo TEXT_FILE=$TEXT_FILE_PROD > .env.local
    - echo BOT_TOKEN=$BOT_TOKEN_PROD >> .env.local
    - echo HTTP_URL=$HTTP_URL_PROD >> .env.local
    - echo LOGSTASH_TYPE=c3po.sibset.ru >> .env.local
    - echo LOG_LEVEL=info >> .env.local
    - npm i
    - cross-env DATABASE_URI=$PROD_SIB_DATABASE_URI node_modules/.bin/sequelize-cli db:migrate
    - pm2 startOrReload ecosystem.json --only server --env production
    - pm2 startOrReload ecosystem.json --only worker --env production
  only:
    - master
  tags:
    - prod
  when: manual
