stages:
  - deploy_dev
  - deploy_prod

deploy_dev:
  stage: deploy_dev
  environment:
    name: development
  script:
    - sudo rsync -acv --progress --delete --exclude="node_modules" --exclude=".gitignore" --exclude=".git" ./ /fs/www/dev-finn.sibset.ru
    - cd /fs/www/dev-finn.sibset.ru
    - echo NODE_ENV=development > .env.local
    - echo BOT_TOKEN=$BOT_TOKEN_DEV >> .env.local
    - echo LOGSTASH_TYPE=dev-c3po.sibset.ru >> .env.local
    - echo LOG_LEVEL=debug >> .env.local
    - echo DB_USER=$DB_USER_DEV >> .env.local
    - echo DB_PASS=$DB_PASS_DEV >> .env.local
    - echo DB_NAME=$DB_NAME_DEV >> .env.local
    - echo DB_HOST=$DB_HOST_DEV >> .env.local
    - npm i
    - pm2 start index.js
  only:
    - master
    - /^Web-/
  tags:
    - develop
  when: manual

deploy_prod:
  stage: deploy_prod
  environment:
    name: production
  script:
    - sudo rsync -acv --progress --delete --exclude="node_modules" --exclude=".gitignore" --exclude=".git" ./ /fs/www/finn.sibset.ru
    - echo NODE_ENV=production > .env.local
    - echo BOT_TOKEN=$BOT_TOKEN_PROD >> .env.local
    - echo LOGSTASH_TYPE=c3po.sibset.ru >> .env.local
    - echo LOG_LEVEL=info >> .env.local
    - echo DB_USER=$DB_USER_PROD >> .env.local
    - echo DB_PASS=$DB_PASS_PROD >> .env.local
    - echo DB_NAME=$DB_NAME_PROD >> .env.local
    - echo DB_HOST=$DB_HOST_PROD >> .env.local
    - npm i
    - pm2 startOrReload index.js
  only:
    - master
  tags:
    - prod
  when: manual
